spring.application.name=ProductInventoryAPI

spring.output.ansi.enabled=ALWAYS

# 1. Using the 'mem' protocol (This avoids the "File Not Found" error)
spring.datasource.url=jdbc:h2:mem:productinventorydb;DB_CLOSE_DELAY=-1

# 2. Basic credentials
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 3. Enable the browser interface
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console

# 4. Prevent Spring from generating a random name
spring.datasource.generate-unique-name=false

# 5. Let Hibernate create the 'books' table automatically
spring.jpa.hibernate.ddl-auto=update

